version: '3.3'
services:
  app:
    build:
      context: .
    container_name: spring_boot_app
    restart: always
    environment:
      SPRING_PROFILE_ACTIVE: 'default'
      SPRING_DATASOURCE_URL: 'jdbc:mysql://db:3306/app_db'
      SPRING_DATASOURCE_USERNAME: 'app_user'
      SPRING_DATASOURCE_PASSWORD: 'P@ssw0rd'
      SPRING_JPA_DATABASE_PLATFORM: 'org.hibernate.dialect.MySQLDialect'
      SPRING_JPA_HIBERNATE_DDL_AUTO: 'none'
      SPRING_SQL_INIT_MODE: 'always'
      SPRING_SQL_INIT_CONTINUE_ON_ERROR: 'true'

    ports:
      - '8080:8080'
    expose:
      - '8080'
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:8.0.28
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'app_db'
      MYSQL_USER: 'app_user'
      MYSQL_PASSWORD: 'P@ssw0rd'
      MYSQL_ROOT_PASSWORD: 'P@ssw0rd'

    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql: