spring:
  profiles:
    active: test
  datasource:
    url: jdbc:mysql://localhost:3306/app_db
    username: app_user
    password: P@ssw0rd
    driverClassName: com.mysql.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      continue-on-error: true
