spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/app_db
    username: app_user
    password: P@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true