spring:
  profiles:
    active: default
  datasource:
    url: jdbc:h2:mem:app_db
    username: app_user
    password: P@ssw0rd
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      continue-on-error: true
