name: PR Validation

on:
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.1
      with:
        arguments: clean check
        build-root-directory: backend
    - name: Generate JaCoCo Badge
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-branches-badge: true
        jacoco-csv-file: backend/build/reports/jacoco/test/jacocoTestReport.csv
