name: Gradle check

on:
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: gradle chmod
      run: chmod +x ./backend/gradlew
    - name: go to backend directory
      run: cd backend
    - name: gradle clean check
      run: ./gradlew clean check
#    - name: Build with Gradle
#      uses: gradle/gradle-build-action@v2
#      with:
#        arguments: clean check
#        build-root-directory: backend
#    - uses: actions/upload-artifact@v3
#      with:
#        name: Upload test coverage report
#        path: build/jacoco/index.html
#    - uses: actions/upload-artifact@v3
#      with:
#        name: Upload test result
#        path: build/test-results
